export const SET_LOADER = "SET_LOADER";
export const MY_API_ERROR = "MY_API_ERROR";
export const OPEN_IMAGE_SHOW_MODAL = "OPEN_IMAGE_SHOW_MODAL";
export const SET_TAB_HEADER_STATE = "SET_TAB_HEADER_STATE";
export const SET_TAB_SPECIAL_PRODUCT_STATE = "SET_TAB_SPECIAL_PRODUCT_STATE";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const SET_ALL_CATEGORY = "SET_ALL_CATEGORY";

export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const SET_ALL_SUB_CATEGORY = "SET_ALL_SUB_CATEGORY";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const SET_ALL_PRODUCT = "SET_ALL_PRODUCT";

export const GET_ALL_PRODUCT_SECTION = "GET_ALL_PRODUCT_SECTION";
export const SET_ALL_PRODUCT_SECTION = "SET_ALL_PRODUCT_SECTION";

export const GET_PRODUCT_VIA_PAGINATION = "GET_PRODUCT_VIA_PAGINATION";

export const GET_SORT_VALUE = "GET_SORT_VALUE";
export const SET_SORT_VALUE = "SET_SORT_VALUE";

export const GET_FILTER_PRODUCT = "GET_SORT_VALUE";
export const SET_FILTER_PRODUCT = "SET_SORT_VALUE";

export const GET_ALL_LANGUAGES = "GET_ALL_LANGUAGES";
export const SET_ALL_LANGUAGES = "SET_ALL_LANGUAGES";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";

export const GET_USER_CART = "GET_USER_CART";
export const SET_USER_CART = "SET_USER_CART";

export const UPDATE_CART_ITEM_LISST = "UPDATE_CART_ITEM_LISST";
export const SET_UPDATE_CART_ITEM_LIST = "SET_UPDATE_CART_ITEM_LIST";

export const GET_USER_WISHLIST = "GET_USER_WISHLIST";
export const SET_USER_WISHLIST = "SET_USER_WISHLIST";

export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const SET_USER_ADDRESS = "SET_USER_ADDRESS";

export const GET_USER_COUNTRY = "GET_USER_COUNTRY";
export const SET_USER_COUNTRY = "SET_USER_COUNTRY";

export const GET_USER_STATE = "GET_USER_STATE";
export const SET_USER_STATE = "SET_USER_STATE";

export const GET_APP_INFO = "GET_APP_INFO";
export const SET_APP_INFO = "SET_APP_INFO";

export const CHECK_USER_SESSION = "CHECK_USER_SESSION";

export const GET_PRODUCT_RATING_REVIEW = "GET_PRODUCT_RATING_REVIEW";
export const SET_PRODUCT_RATING_REVIEW = "SET_PRODUCT_RATING_REVIEW";

export const GET_LEGAL_PAGE_LIST = "GET_LEGAL_PAGE_LIST";
export const SET_LEGAL_PAGE_LIST = "SET_LEGAL_PAGE_LIST";

export const GET_HOME_SLIDER = "GET_HOME_SLIDER";
export const SET_HOME_SLIDER = "SET_HOME_SLIDER";

export const GET_APP_SOCIAL_LINK = "GET_APP_SOCIAL_LINK";
export const SET_APP_SOCIAL_LINK = "SET_APP_SOCIAL_LINK";

export const GET_APP_BLOGS = "GET_APP_BLOGS";
export const SET_APP_BLOGS = "SET_APP_BLOGS";

export const GET_USER_ORDER = "GET_USER_ORDER";
export const SET_USER_ORDER = "SET_USER_ORDER";