// Dashboard Main File
export const CONTROL_SIDE_BAR = "CONTROL_SIDE_BAR";
export const PAGE_ERROR_NAVIGATION = "PAGE_ERROR_NAVIGATION";

export const GET_ADD_IMAGE_MODAL_STATE = "GET_ADD_IMAGE_MODAL_STATE";


export const SET_LOADER = "SET_LOADER";
export const MY_API_ERROR = "MY_API_ERROR";
export const ADMIN_LOGIN = "ADMIN_LOGIN"

export const GET_TESTING_API = "GET_TESTING_API";
export const SET_TESTING_API = "SET_TESTING_API";

export const GET_ADMIN_PERMISSION = "GET_ADMIN_PERMISSION";
export const SET_ADMIN_PERMISSION = "SET_ADMIN_PERMISSION";

export const GET_ADMIN_PERMISSION_FAMILY = "GET_ADMIN_PERMISSION_FAMILY";
export const SET_ADMIN_PERMISSION_FAMILY = "SET_ADMIN_PERMISSION_FAMILY";

export const GET_ADMIN_ROLE = "GET_ADMIN_ROLE";
export const SET_ADMIN_ROLE = "SET_ADMIN_ROLE";

export const GET_ADMIN_MANAGER = "GET_ADMIN_MANAGER";
export const SET_ADMIN_MANAGER = "SET_ADMIN_MANAGER";

export const CHECK_AUTH_ROUTE = "CHECK_AUTH_ROUTE";
export const SET_AUTH_ROUTE_DATA = "SET_AUTH_ROUTE_DATA";

export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const SET_CATEGORY_DATA = "SET_CATEGORY_DATA";

export const GET_ALL_SUB_CATEGORY_DATA = "GET_ALL_SUB_CATEGORY_DATA";
export const SET_ALL_SUB_CATEGORY_DATA = "SET_ALL_SUB_CATEGORY_DATA";

export const GET_SUB_CATEGORY_DATA = "GET_SUB_CATEGORY_DATA";
export const SET_SUB_CATEGORY_DATA = "SET_SUB_CATEGORY_DATA";

export const GET_ATTRIBUTE_DATA = "GET_ATTRIBUTE_DATA";
export const SET_ATTRIBUTE_DATA = "SET_ATTRIBUTE_DATA"

export const GET_ALL_ATTRIBUTE_FAMILY = "GET_ALL_ATTRIBUTE_FAMILY";
export const SET_ALL_ATTRIBUTE_FAMILY = "SET_ALL_ATTRIBUTE_FAMILY";

export const GET_ATTRIBUTE_FAMILY_DATA = "GET_ATTRIBUTE_FAMILY_DATA";
export const SET_ATTRIBUTE_FAMILY_DATA = "SET_ATTRIBUTE_FAMILY_DATA"

export const GET_COLOR_VARIANT_DATA = "GET_COLOR_VARIANT_DATA";
export const SET_COLOR_VARIANT_DATA = "SET_COLOR_VARIANT_DATA"

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS"

export const GET_ADMIN_NAV_SIDERBAR_LIST = "GET_ADMIN_NAV_SIDERBAR_LIST";
export const SET_ADMIN_NAV_SIDERBAR_LIST = "SET_ADMIN_NAV_SIDERBAR_LIST";

export const GET_TEST_ALL_PRODUCT = "GET_TEST_ALL_PRODUCT";
export const SET_TEST_ALL_PRODUCT = "SET_TEST_ALL_PRODUCT"

export const GET_PRODUCT_TITLES = "GET_PRODUCT_TITLES";
export const SET_PRODUCT_TITLES = "SET_PRODUCT_TITLES"

export const GET_APP_LANGUAGE = "GET_APP_LANGUAGE";
export const SET_APP_LANGUAGE = "SET_APP_LANGUAGE"

// CATLOG LANGUAGE MODAL STATE 
export const CATEGORY_MODAL_STATE = "CATEGORY_MODAL_STATE"
export const SUBCATEGORY_MODAL_STATE = "SUBCATEGORY_MODAL_STATE"
export const PRODUCT_MODAL_STATE = "PRODUCT_MODAL_STATE"
export const ATTRIBUTE_MODAL_STATE = "ATTRIBUTE_MODAL_STATE"
export const ATTRIBUTEFAMILY_MODAL_STATE = "ATTRIBUTEFAMILY_MODAL_STATE"
export const COLOR_MODAL_STATE = "COLOR_MODAL_STATE"

export const GET_STATE = "GET_STATE";
export const SET_STATE = "SET_STATE";

export const GET_COUNTRY = "GET_COUNTRY";
export const SET_COUNTRY = "SET_COUNTRY";

export const GET_APPLICATION_INFO = "GET_APPLICATION_INFO";
export const SET_APPLICATION_INFO = "SET_APPLICATION_INFO";

export const GET_ORDER_STATUS_TITLE = "GET_ORDER_STATUS_TITLE";
export const SET_ORDER_STATUS_TITLE = "SET_ORDER_STATUS_TITLE";

export const GET_ADMIN_CUSTOMER_LIST = "GET_ADMIN_CUSTOMER_LIST";
export const SET_ADMIN_CUSTOMER_LIST = "SET_ADMIN_CUSTOMER_LIST";

export const GET_ADMIN_CUSTOMER_CART_LIST = "GET_ADMIN_CUSTOMER_CART_LIST";
export const SET_ADMIN_CUSTOMER_CART_LIST = "SET_ADMIN_CUSTOMER_CART_LIST";

export const GET_ADMIN_PRODUCT_REVIEW = "GET_ADMIN_PRODUCT_REVIEW";
export const SET_ADMIN_PRODUCT_REVIEW = "SET_ADMIN_PRODUCT_REVIEW";

export const GET_ADMIN_ORDER = "GET_ADMIN_ORDER";
export const SET_ADMIN_ORDER = "SET_ADMIN_ORDER";

export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY";
export const SET_TRANSACTION_HISTORY = "SET_TRANSACTION_HISTORY";

export const GET_TRANSACTION_SEARCH_HISTORY = "GET_TRANSACTION_SEARCH_HISTORY";
export const SET_TRANSACTION_SEARCH_HISTORY = "SET_TRANSACTION_SEARCH_HISTORY";

export const GET_LEGAL_PAGES = "GET_LEGAL_PAGES";
export const SET_LEGAL_PAGES = "SET_LEGAL_PAGES";

export const GET_ADMIN_SLIDER = "GET_ADMIN_SLIDER";
export const SET_ADMIN_SLIDER = "SET_ADMIN_SLIDER";

export const GET_ADMIN_BLOGS = "GET_ADMIN_BLOGS";
export const SET_ADMIN_BLOGS = "SET_ADMIN_BLOGS";

export const GET_ADMIN_COUPONS = "GET_ADMIN_COUPONS";
export const SET_ADMIN_COUPONS = "SET_ADMIN_COUPONS";

export const GET_ADMIN_THEME = "GET_ADMIN_THEME";
export const SET_ADMIN_THEME = "SET_ADMIN_THEME";

export const GET_WEBSITE_THEME = "GET_WEBSITE_THEME";
export const SET_WEBSITE_THEME = "SET_WEBSITE_THEME";

export const GET_APP_SOCAIL_LINK = "GET_APP_SOCAIL_LINK";
export const SET_APP_SOCAIL_LINK = "SET_APP_SOCAIL_LINK";

export const GET_CITY = "GET_CITY";
export const SET_CITY = "SET_CITY";

export const GET_PINCODE = "GET_PINCODE";
export const SET_PINCODE = "SET_PINCODE";

export const CHANGE_API_SETTING_STATE = "CHANGE_API_SETTING_STATE";

export const GET_CONTACT_US_QUERY = "GET_CONTACT_US_QUERY";
export const SET_CONTACT_US_QUERY = "SET_CONTACT_US_QUERY";

export const GET_USER_TRACK_LOG = "GET_USER_TRACK_LOG";
export const SET_USER_TRACK_LOG = "SET_USER_TRACK_LOG";
